### ISSUE TITLE
Migrate to pin-project-lite

### ISSUE THREAD

**Issue by davidpdrsn** [tower-rs/tower-http#115]
Tower recently migrated to pin-project-lite (https://github.com/tower-rs/tower/pull/595) so it makes sense to do the same for tower-http. It should be a fairly mechanical operation. Off the top of my head tower-http isn't using any of pin-projects more advanced features.

**Comment by tesaguri** [comment]
Migrating `compression::Body` and `dexompression::Body` would be difficult because their inner `enum`s have `#[cfg(...)]` attributes on its variants, which `pin-project-lite` does not support yet (<https://github.com/taiki-e/pin-project-lite/issues/3>). There is a workaround (<https://github.com/taiki-e/pin-project-lite/issues/3#issuecomment-774461161>) like the one I originally used in <https://github.com/tower-rs/tower-http/pull/41>, though it would introduce a huge macro.
