### ISSUE TITLE
Handle Range Requests in ServeDir

### ISSUE THREAD

**Issue by theduke** [tower-rs/tower-http#128]
## Feature Request

`ServeDir` currently does not respect [Range headers](https://developer.mozilla.org/en-US/docs/Web/HTTP/Range_requests).

This is pretty important for serving larger files like videos, or for allowing browsers to resume downloads.

**Comment by davidpdrsn** [comment]
We can probably get inspiration from [warp's implementation](https://github.com/seanmonstar/warp/blob/master/src/filters/fs.rs).

**Comment by theduke** [comment]
I also remember the `actix-web` implementation to be pretty solid.

I think it does a few more things like adding `content-disposition` headers.

**Comment by theduke** [comment]
Implementation is here: https://github.com/actix/actix-web/tree/master/actix-files/src

Quite a bit more advanced and configurable.

**Comment by davidpdrsn** [comment]
I don't mind changing the internals, as long as we don't introduce breaking changes.

**Comment by theduke** [comment]
I'll draft a PR.
I already refactored the actix-web code once for a warp project.

If it's too similar it would mean adding their license though, I reckon.

Ideally actix-web could somehow be convinced to share the implemenation...

**Comment by davidpdrsn** [comment]
> If it's too similar it would mean adding their license though, I reckon.

For sure.

> Each project implementing this from scratch, usually in an incomplete fashion, was one of my big annoyances with the state of Rust frameworks.

Thats the whole purpose of tower-http. To provide building blocks that aren't framework specific :)

**Comment by apps4uco** [comment]
Hi, Im very interested in this. Would it be possible to consider in the api, not just reading from files, but reading from database BLOBs/CLOBs, sled database and block caches like bcache and nbd.

**Comment by davidpdrsn** [comment]
Is there one way to read from all those things or would we have to have different implementations for thing to read from?

**Comment by programatik29** [comment]
Anyone working on this?

**Comment by davidpdrsn** [comment]
I don't believe so.

**Comment by apps4uco** [comment]
I found a crate that could be adapted/incorporated for this (dependencies include http, http-body)

<https://crates.io/crates/http-serve>

"Rust helpers for serving HTTP GET and HEAD responses with hyper 0.14.x and tokio.

This crate supplies two ways to respond to HTTP GET and HEAD requests:

the serve function can be used to serve an Entity, a trait representing reusable, byte-rangeable HTTP entities. Entity must be able to produce exactly the same data on every call, know its size in advance, and be able to produce portions of the data on demand"

**Comment by davidpdrsn** [comment]
I don't its appropriate for tower-http to depend on other crates for that. I would like us to have full control over the implementation. However we can of course draw inspiration from its features or tests.

**Comment by MarcusGrass** [comment]
In the above PR https://github.com/tower-rs/tower-http/pull/173 I made a dirty implementation by copying and editing [Tokio's ReaderStream](https://docs.rs/tokio-util/0.6.9/src/tokio_util/io/reader_stream.rs.html#10-55) to check if that would be a working implementation and it does work but is it reasonable? 
The problem we encounter is that we want to be able to create a poll-eable body to be able to get the headers out first and then the body later, so we can't read the file in our async context. 

Something we could do is what this PR does [here](https://github.com/MarcusGrass/tower-http/blob/read_partial/tower-http/src/services/fs/read_stream.rs) and allow you to specify the number of bytes you want to read. You will still over-read from the file by at most the buffer-size (the unwanted bytes are discarded) the implementation is still a bit dirty and the over-read could probable be fixed but just looking at it quickly that might require unsafe code.

Another solution which @Nehliin suggested and implemented [here](https://github.com/tower-rs/tower-http/blob/59736568112731070300a030082c1b4949431c7a/tower-http/src/services/fs/serve_file.rs#L132) is to send the actual read as a future and then we could convert that to a body. [Actix does something similar](https://github.com/qrvaelet/actix-web/blob/master/src/fs.rs#L387) but they spawn a task for it and sync reads the file in that, but I think @Nehliin 's approach is philosophically the same.

The PR's solution requires you to first seek the file, then supply it as a reader, if we go with the other approach we could-in a future seek, construct a buffer with the correct file, then read_exact into it. 

Something @Nehliin mentioned was that the "box-pin/spawn future" approach will force us to keep the entire file in-mem at once which might be undesirable from for example a ddos perspective if for some reason someone requests a huge range so that speaks for the first solution. Me and @davidpdrsn spoke about this a bit and we'd would love some feedback on approaches to take here.

**Comment by Nehliin** [comment]
I think we would at least need to keep the entire requested range in memory not necessarily the entire file but maybe that's what you ment @MarcusGrass? It would be nice to be able to stream the range since otherwise malicious users could ask for the entire file via range request instead of normal `GET` request which avoids keeping everything in memory. If there was a way to specify the max range allowed to be requested you could mitigate impact of potential malicious use at least.

**Comment by MarcusGrass** [comment]
> I think we would at least need to keep the entire requested range in memory not necessarily the entire file but maybe that's what you ment @MarcusGrass? It would be nice to be able to stream the range since otherwise malicious users could ask for the entire file via range request instead of normal `GET` request which avoids keeping everything in memory. If there was a way to specify the max range allowed to be requested you could mitigate impact of potential malicious use at least.

I might be off in my understanding of some stuff in web and how it relates to Tower but I figured if you supply a pollable body you could stream it over the connection, if that theory holds up then the PR's solution is better from a memory usage point of view. If you can't do that then the solutions should have the same memory footprint if I'm not mistaken, I haven't looked into the different file read method's implementations close enough to be certain but I assumed that if you supply a buffer that's shorter than the file that buffer would be filled without having to rip the entire file into memory, but again I could be mistaken here.

**Comment by Nehliin** [comment]
I meant the suggestion of Box::pin the future which would use `read_exact` not the PR you have posted!

**Comment by MarcusGrass** [comment]
> I meant the suggestion of Box::pin the future which would use `read_exact` not the PR you have posted!

Sorry my response was messy or maybe I missed something but what I meant is this:
With the `AsyncBody` polling we ideally get a case where we only keep the buffer's capacity in memory at a given time, whereas in the `file.read_exact` case we will read the entire range into memory at once, which could theoretically be usize::MAX, I checked out the docs and if I didn't misunderstand we would not read any more bytes than necessary into memory at a given time in that case, so in either case we at least don't read the entire file
