### ISSUE TITLE
Preflight response access control headers should match request

### ISSUE THREAD

**Issue by tqwewe** [tower-rs/tower-http#194]
### Version

`tower-http v0.2.0`

### Platform

`Darwin MacBook-Pro-2 21.1.0 Darwin Kernel Version 21.1.0`

### Description

Preflight response should match request `access-control-allow-origin` and `access-control-allow-headers` and should not use wild card `*`.

Currently, cors issues occur due to preflight response headers not matching the requested headers for origin and allowed headers. The response should copy the headers from the request (if allowed in the configuration).

<https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS#credentialed_requests_and_wildcards>

> - The server **must not** specify the "`*`" wildcard for the `Access-Control-Allow-Origin` response-header value, but must instead specify an explicit origin; for example: `Access-Control-Allow-Origin: https://example.com`
> - The server **must not** specify the "`*`" wildcard for the `Access-Control-Allow-Headers` response-header value, but must instead specify an explicit list of header names; for example, `Access-Control-Allow-Headers: X-PINGOTHER, Content-Type`
> - The server must not specify the "`*`" wildcard for the `Access-Control-Allow-Methods` response-header value, but must instead specify an explicit list of method names; for example, `Access-Control-Allow-Methods: POST, GET`

The above rules don't seem to be handled correctly by tower-http.

**Comment by jplatte** [comment]
I agree that there is a problem here, but I don't think the suggested solution makes sense.

IMO `CorsLayer::permissive` should simply not include `allow_credentials(true)` and we should add a note to the docs that you can't use wildcards together with `allow_credentials(true)`. Attempting to bypass the rules documented at the provided link by having the server respond with different CORS headers based on the request headers will inevitably lead to security vulnerabilities. Additionally, I'm pretty sure preflight requests don't include all of the headers of the main request, so for `allow_headers` this wouldn't work anyways.

**Comment by davidpdrsn** [comment]
> A future version could potentially even panic when attempting to use a CORS middleware that sets a wildcard in combination with allow_credentials(true) since that is apparently never correct.

iirc actix’s cors implementation does that. Worth investigating for sure.

**Comment by tqwewe** [comment]
@jplatte
> I'm pretty sure preflight requests don't include all of the headers of the main request, so for allow_headers this wouldn't work anyways.

I believe they do under `access-control-request-headers`, but I could be wrong. But this is what fixed it for me.

Is there any suggestion on how to get cors working correctly with the current version of `tower-http`? From what I understood, the preflight response should match (or cover more than) the headers of the request for `access-control-allow-origin`, `access-control-allow-headers`, `access-control-allow-methods`.

Perhaps along with the `any()` function, there should be an `all()` function which just lists all the standard values for the headers.

**Comment by meh** [comment]
We're hitting this issue as well, `warp` also behaves like this AFAICT, or at least everything was working until we moved from `warp` to `axum`.

People will try to find work-arounds for this, or just re-implement their own CORS layer to make it work like this (which is what I'll have to do if I want my thing to work at all).

**Comment by davidpdrsn** [comment]
I don't know when I'll have time to fix this so contributions would be much appreciated!

**Comment by tqwewe** [comment]
@meh and others,

This code may help:

```rust
let cors = CorsLayer::new()
    .allow_credentials(true)
    .allow_headers(vec![
        header::ACCEPT,
        header::ACCEPT_LANGUAGE,
        header::AUTHORIZATION,
        header::CONTENT_LANGUAGE,
        header::CONTENT_TYPE,
    ])
    .allow_methods(vec![
        Method::GET,
        Method::POST,
        Method::PUT,
        Method::DELETE,
        Method::HEAD,
        Method::OPTIONS,
        Method::CONNECT,
        Method::PATCH,
        Method::TRACE,
    ])
    .allow_origin(Origin::exact(
        "http://localhost:3000".parse().unwrap(), // Make sure this matches your frontend url
    ))
    .max_age(Duration::from_secs(60 * 60));
```

**Comment by jplatte** [comment]
Instead of `AnyOr<_>`, how about representing all of [`allow_headers`, `allow_origin`, `allow_methods`, `expose_headers`] as their own type similar to the `Origin` type, but have those types simply hold a boxed `FnMut` that can access the request? Then those types can have constructors like `Origin::any()` and `Origin::from_list(vec![...])` and `Origin::from_request_origin()`. That makes it easy to do the thing that some people want and allow anything including headers, which could also be exposed as another `Cors` constructor (though I think the current `Cors::permissive()` should still exist in some form, just without the ineffective `allow_credentials(true)`).

**Comment by Venryx** [comment]
I lost 3 hours to this!

My server in production (but not development) just kept rejecting connection attempts, without any error message in my load-balancer other than the message: `"'502 Bad Gateway' caused by: dial tcp 10.2.1.253:3105: connect: connection refused"`

I eventually found this thread, which I thought might be the cause.

FWIW, the `cors` module in NodeJS (which I had used before the Rust rewrite) supports the OP's feature-request as well: https://github.com/expressjs/cors/blob/734e080a47c6ff5554b61cb43f7bd65e5909b30c/lib/index.js#L98

**Comment by davidpdrsn** [comment]
@jplatte @tqwewe would either of you be up for trying to implement a fix for this? Tbh I'm not quite sure I understand the issue 🤔

I'm fine with making breaking changes if it means we get a nice and consistent API 😊

**Comment by jplatte** [comment]
I also don't get how this is related to server-side errors in a load balancer, but will try to find some time to implement my suggested changes.

**Comment by Venryx** [comment]
> I also don't get how this is related to server-side errors in a load balancer

Sorry, yes, my mistake; I was conflating two issues with each other.

There was an issue with the list of allowed headers not including all the entries it needed (for which the OP's suggestion would help, since my requests can't use `*` due to having authentication included), but that was not the cause of the error message shown in my previous comment. (that was due to a mistake in my socket-address)

**Comment by jplatte** [comment]
First PR is merged, second pending review, third (but still not final) PR up at #224.

**Comment by szarykott** [comment]
Shall it be resolved soon?

I tried using tower-http's CORS layer today and it still behaves incorrectly in v0.2.5

In OPTIONS request `Access-Control-Allow-Headers` still uses `*` if `Access-Control-Allow-Credentials` is `true` (instead of copy-pasting allowed headers from request) and in subsequent responses (using other methods, e.g POST) it attaches `Access-Control-Allow-Origin: *` with `Access-Control-Allow-Credentials : true` (even though `Origin` is specified in request). I am not even sure if attaching CORS headers to subsequent responses is correct. 

In any case I can provide reproducible example if need be.

**Comment by jplatte** [comment]
I'm not sure when I'll get to PRing the last part of this (all refactoring I wanted to do first is done). Either way it won't be part of 0.2.x.

**Comment by jplatte** [comment]
> In OPTIONS request `Access-Control-Allow-Headers` still uses `*` if `Access-Control-Allow-Credentials` is `true` (instead of copy-pasting allowed headers from request)

I don't like the option of changing the meaning of `.allow_headers(Any)` depending on whether credentials are allowed. I will introduce something like `.allow_headers(AllowHeaders::copy_from_request())` which will fill this role. We could consider panicking for combination of `.allow_credentials(true)` and `Any` to make this error more obvious (wdyt @davidpdrsn?).

> and in subsequent responses (using other methods, e.g POST) it attaches `Access-Control-Allow-Origin: *` with `Access-Control-Allow-Credentials : true` (even though `Origin` is specified in request). I am not even sure if attaching CORS headers to subsequent responses is correct.

This is correct as far as I can tell, see

* https://fetch.spec.whatwg.org/#http-responses
* https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS#examples_of_access_control_scenarios (second sequence diagram shows `Access-Control-Allow-Origin` on both preflight and subsequent request)

**Comment by davidpdrsn** [comment]
Panicking is fine with me.

**Comment by szarykott** [comment]
@jplatte 

As for the first part (first quote), such a solution is super fine.

But for the second, I think I should stress that part where `Access-Control-Allow-Origin: *` is returned with `Control-Allow-Credentials : true` which is named incorrect by the OP of this issue. `Access-Control-Allow-Origin` should copy `Origin` from the request in case of allowed credentials. (Apologies if there is a way to do so with current impl)

**Comment by jplatte** [comment]
There is no way to do this with the current implementation. With the new implementation (that's almost ready), it will be possible with

```rust
CorsLayer::new()
    .allow_credentials(true)
    .allow_origin(AllowOrigin::mirror_request()) 
```

trying to instead use

```rust
CorsLayer::new()
    .allow_credentials(true)
    .allow_origin(Any) 
```

will result in a panic.

Does that sounds reasonable to you?
