### ISSUE TITLE
Could add a parameter `error` in the api: `on_failure`?

### ISSUE THREAD

**Issue by goldwind-ting** [tower-rs/tower-http#239]
## Feature Request
add a parameter `Error` in the method `on_failure`.
### Motivation
sometime want to record error in the `span` in the [api](https://docs.rs/tower-http/latest/tower_http/trace/trait.OnFailure.html#tymethod.on_failure).

**Comment by davidpdrsn** [comment]
The intention is that your classifier can extract whatever data it needs from the error (in `classify_error`), which will then be passed to `on_failure`. Therefore I'm not sure passing the whole error is appropriate 🤔

Can you share more about your use case for returning errors in the first place? I generally don't recommend servers returning errors at all, since it'll terminate the connection without sending a response. Thats why, in axum, we require services to use `Infallible` as the error type.

**Comment by goldwind-ting** [comment]
When the `on_failure` is called, it means the request had failed, so if the error could pass to this callback, the servers can overwrite the callback and handle errors uniformly.

**Comment by davidpdrsn** [comment]
Can you share more about your use case? Are you writing a server or a client? Are you using a framework, if so which? How you do want to report responses with a non-success code, which dont have any errors?

**Comment by goldwind-ting** [comment]
I am not writing servers and clients.
even through the lib exposes an api `on_failure`, why not pass the error when the request failed?
of course, it is also ok without `error` argument, I will close the issue.

**Comment by davidpdrsn** [comment]
I need to know about your use case to know if changing the API for it is appropriate.
