### ISSUE TITLE
Add body message to StatusInRangeFailureClass::StatusCode

### ISSUE THREAD

**Issue by Gricha** [tower-rs/tower-http#268]
### Motivation

Currently, this Classifier allows for catching various error codes and mark them as errors for logging purposes. The error code alone oftentimes isn't enough to debug the actual issue. For instance in 400 Bad Request, it's not uncommon to inject some string into response body that describes the reason for the error. For instance lack of specific resource ID.

### Proposal

To combat that, I propose changing `StatusInRangeFailureClass::StatusCode` to carry `Option<String>` (or other form of Body encoding that maybe is more broadly compatible). This will allow for reporting failure reason directly int he `on_failure` block of `TraceLayer`.

### Alternatives

I'm currently unsure of alternatives to that other than not using `StatusInRangeFailureClass` in my code.

**Comment by davidpdrsn** [comment]
`Trace`'s callbacks aren't async so I'm afraid that not possible. You cannot load the response body without async since its basically an async stream.

I general I'd also recommend against relying on `Trace` to handle all your error reporting, which it seems is what you're going for. Instead I'd recommend handlers/routes to report their errors themselves. They have all the context necessary to produce rich errors reports that are gonna be much more helpful than the status code and response body.

If you're using axum (from reading https://github.com/tower-rs/tower-http/issues/269 it seems you are) I'd recommend doing something like this:

```rust
async fn handler() -> Result<(), Error> {
    // ...
}

// an error type used by all your handlers
// could also be `struct Error(anyhow::Error)`
enum Error {
    SomethingWentWrong,
}

impl IntoResponse for Error {
    fn into_response(self) -> axum::response::Response {
        match self {
            Error::SomethingWentWrong => {
                // report the error with as much context as you need
                tracing::error!("something went wrong");

                // return a response
                StatusCode::INTERNAL_SERVER_ERROR.into_response()
            },
        }
    }
}
```

**Comment by davidpdrsn** [comment]
Exactly 😊
