### ISSUE TITLE
Client-side redirection middleware

### ISSUE THREAD

**Issue by tesaguri** [tower-rs/tower-http#78]
A middleware that handles client-side HTTP redirections would be nice, I think.

The middleware needs to rewrite the URI and request method of the request based on the response, and since `tower::retry::Policy` does not allow you to modify the request (IIUIC), we have to implement it as an independent middleware.

It would also be nice to have a mechanism akin to [`reqwest::redirect::Policy`] to control the behavior of redirection e.g. to limit the number of successive redirections and to restrict the origin of the destination.

[`reqwest::redirect::Policy`]: https://docs.rs/reqwest/0.11.2/reqwest/redirect/struct.Policy.html

If this idea looks fine to you, I'd be happy to work on a PR.

**Comment by davidpdrsn** [comment]
This totally makes sense to have so feel free to give it shot!

The issue that I've run into when building this is how to clone the request. `http::Request<B>` isn't `Clone` even if `B` is `Clone`. I guess thats because `http::Extensions` isn't `Clone`.

At Embark we actually an `http` compatible client that we're experimenting this which does support redirects. It uses its own body type which is defined as

```rust
enum Body {
    Bytes(bytes::Bytes),
    Hyper(hyper::Body),
}
```

This then has an `fn try_clone(&self) -> Option<Self>` method that succeeds if the body contains a `Bytes` otherwise it fails.

However when actually cloning an `http::Request<Body>` it doesn't include the extensions on the clone. I'm honestly not sure if that could lead to bugs but its something to think about should we decide to include something in `tower-http`.

It seems reqwest gets around this by having its own request type which doesn't have extensions and is therefore cloneable if the body is. That doesn't appear to be something they expose though.
